### PR TITLE
React spring 9 (Bonus: Fixed bad spelling)

### LINKED ISSUE #210: TypeError: Cannot read properties of undefined (reading 'getValue')
I'm using your great module on my all projects but i couldn't implement to new one.
I got this error.

my dependencies: 
    "react-spring-bottom-sheet": "^3.4.0",
    "next": "12.1.4",
    "react-dom": "18.0.0",

### PR DESCRIPTION
**Pull request by AshMW2724**
I have gone through and upgraded react-spring to `v9.4.5`. This PR needs to be thourghly reviewed. I have made sure to test this PR before creating it but obviously please test it again before merging or closing.

This will resolve #210

### CODE REVIEW

**Comment by AshMW2724** [comment]
@stipsan could you possibly review this PR?

**Comment by RezaHeydarii** [comment]
@stipsan  can you please review this? we can't use bottom sheet in react 18 right now.

**Comment by stipsan** [comment]
Hello! 

I've published the changes in this PR under the `alpha` dist tag:
```bash
$ npm i react-spring-bottom-sheet@alpha
```

Test it out and if it doesn't turn out to cause a breaking change I'll merge and release this as `v3.5.0` when I'm back in Oslo (I'm traveling atm as it's my vacation 😉 )

Cheers!

**Comment by AshMW2724** [comment]
Thank you!

I've discovered some pretty big issues i'm working on fixing right now.

**Comment by stipsan** [comment]
Oki @AshMW2724 if you run into too many issues it's worth knowing I'm working on a more extensive rewrite.

Some of the things in the rewrite is to make it easier to deal with implementation changes in the spring physics and transitions.

First off the state machine is redesigned:
https://stately.ai/registry/editor/share/2300fe11-00d3-4679-b56a-6f57b53508bf

The concept of "cancelling" or delaying a state, is removed. Instead, any transition can be interrupted. A `DRAG` might start during `opening` or `resizing` for example.
Additionally, the snap points state, and other state like current height etc, is done in the state machine context instead of a separate, complicated, react hook.

The new state machine lives here: https://github.com/bottom-sheet/state-machine
And the new general hooks are here: https://github.com/bottom-sheet/react-hooks
And the new WIP implementation using said hooks and state machine lives on the `next` branch: https://github.com/stipsan/react-spring-bottom-sheet/commits/next

I'm splitting things up as I want to support other libraries like possibly Framer Motion, Motion One, or other animation libs and/or gesture libs.

Things are still early and undocumented, and I'm surfacing it with you to help you decide how much effort you want to put into adding React Spring v9 support. It would be best if you didn't end up feeling like you've wasted your time or started a large refactor that ends up in a different direction than where things are headed with the new state machine.

Do with that information as you will 🙂

**Comment by SebastienSusini** [comment]
Hello, when do you think react spring bottom sheet will be available on react 18? thx

**Comment by xsjcTony** [comment]
Hey, @stipsan Are there any updates or plans here? I can't use it in React v18 :( Thanks

**Pull request closed without merging**
